#!/usr/bin/env python3
"""Emit a transient-image TOML for a verbatim ROM function copied into RAM.

Every image registered so far follows one shape: the game copies an
ELF-bounded ROM function to a runtime address and branches to it. Writing those
configs by hand means doing literal-pool arithmetic per image — subtracting the
function's `$d` spans from its extent and translating both through the copy
bias — which is exactly the step where a wrong offset would silently turn data
into decoded instructions.

This derives all of it from the pinned ELF instead:

- the extent is the `STT_FUNC` size, never a guess;
- `[[resume_range]]` blocks cover the `$a`/`$t` code runs only;
- `[[data_range]]` blocks cover the `$d` runs, so no resume alias can decode a
  literal pool;
- the image SHA-1 is computed from the hash-verified ROM.

The caller still supplies the evidence: which ROM function, which runtime
address, and the trace that proves the copy. Nothing here discovers anything.

    python tools/build_transient_image_config.py \
        --rom <private ROM> --elf <goldensun.elf> \
        --func 0x08002cf4 --runtime 0x03007dbc --mode arm \
        --name Func_2cf4_stack_image_03007dbc \
        --note "DMA3 trace #NNNN programs SAD=... DAD=..." \
        --output config/usa/transient-func-2cf4-03007dbc.toml
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))

from import_main_symbols import (  # noqa: E402
    STT_FUNC,
    _mapping_symbols,
    parse_elf32_arm,
)
from verify_rom import EXPECTED_SHA1, sha1_file  # noqa: E402

ROM_BASE = 0x08000000


def code_and_data_runs(image, start: int, end: int) -> list[tuple[int, int, bool]]:
    """Split [start, end) into ELF mapping-symbol runs; True means code."""

    states: dict[int, str] = {}
    for entries in _mapping_symbols(image).values():
        for address, kind, _index in entries:
            if start <= address < end:
                states[address] = kind
    if start not in states:
        # The entry's own mapping symbol may be recorded against another
        # section index; fall back to the caller-declared mode.
        states[start] = "a"
    ordered = sorted(states.items())
    runs: list[tuple[int, int, bool]] = []
    for index, (run_start, kind) in enumerate(ordered):
        run_end = ordered[index + 1][0] if index + 1 < len(ordered) else end
        if run_start >= run_end:
            continue
        is_code = kind != "d"
        if runs and runs[-1][2] == is_code and runs[-1][1] == run_start:
            runs[-1] = (runs[-1][0], run_end, is_code)
        else:
            runs.append((run_start, run_end, is_code))
    return runs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rom", required=True, type=Path)
    parser.add_argument("--elf", required=True, type=Path)
    parser.add_argument("--func", required=True, type=lambda v: int(v, 0))
    parser.add_argument("--runtime", required=True, type=lambda v: int(v, 0))
    parser.add_argument("--mode", required=True, choices=("arm", "thumb"))
    parser.add_argument("--name", required=True)
    parser.add_argument("--note", required=True, help="the trace evidence")
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    rom_path = args.rom.expanduser().resolve()
    actual = sha1_file(rom_path)
    if actual != EXPECTED_SHA1:
        print(f"ERROR: ROM SHA-1 {actual} is not the supported image",
              file=sys.stderr)
        return 2

    image = parse_elf32_arm(args.elf.expanduser().resolve().read_bytes())
    symbol = next(
        (s for s in image.symbols
         if s.symbol_type == STT_FUNC and (s.value & ~1) == args.func
         and s.size > 0),
        None,
    )
    if symbol is None:
        print(f"ERROR: no sized STT_FUNC at 0x{args.func:08x}", file=sys.stderr)
        return 2

    size = symbol.size
    rom = rom_path.read_bytes()
    body = rom[args.func - ROM_BASE : args.func - ROM_BASE + size]
    if len(body) != size:
        print("ERROR: function extent falls outside the ROM", file=sys.stderr)
        return 2
    image_sha1 = hashlib.sha1(body).hexdigest()
    bias = args.runtime - args.func

    lines = [
        f"# GS-011 identity-verified AOT variant for {symbol.name} at "
        f"0x{args.runtime:08x}.",
        "#",
        "# Generated by tools/build_transient_image_config.py from the pinned",
        "# ELF and the hash-verified ROM. The extent is the ELF STT_FUNC size;",
        "# the resume/data split below is the function's own mapping symbols",
        "# translated through the copy bias, not hand arithmetic.",
        "#",
        f"# Evidence: {args.note}",
        "#",
        f"# ELF: {symbol.name} at 0x{args.func:08x}, size {size} (0x{size:x}), "
        f"mode {args.mode}.",
        f"# Image SHA-1 {image_sha1}.",
        "",
        "[program]",
        f'name = "Golden Sun transient {symbol.name} image at '
        f'0x{args.runtime:08x}"',
        f'id = "golden_sun_usa_transient_{symbol.name.lower()}_'
        f'{args.runtime:08x}"',
        f"load_address = 0x{ROM_BASE:08x}",
        "size = 0x00800000",
        f"entry_pc = 0x{args.runtime:08x}",
        "speculative_literal_harvest = false",
        "codegen_shards = 1",
        "",
        "[identity]",
        f'sha1 = "{EXPECTED_SHA1}"',
        "",
        "[[code_copy]]",
        f"runtime_start = 0x{args.runtime:08x}",
        f"source_start = 0x{args.func:08x}",
        f"size = 0x{size:08x}",
        f'name = "transient_{symbol.name}_at_{args.runtime:08x}"',
        f'note = "{args.note}; image SHA-1 {image_sha1}"',
        "",
        "[[extra_func]]",
        f"addr = 0x{args.runtime:08x}",
        f'mode = "{args.mode}"',
        f'name = "{args.name}"',
        f'note = "ELF STT_FUNC entry {symbol.name} installed at the observed '
        'copy destination"',
    ]

    runs = code_and_data_runs(image, args.func, args.func + size)
    for run_start, run_end, is_code in runs:
        section = "resume_range" if is_code else "data_range"
        lines.extend([
            "",
            f"[[{section}]]",
            f"start = 0x{run_start + bias:08x}",
            f"end = 0x{run_end + bias:08x}",
        ])
        if is_code:
            lines.append(f'mode = "{args.mode}"')
            lines.append(
                f'note = "{symbol.name} code run, ROM '
                f'0x{run_start:08x}..0x{run_end:08x}"'
            )
        else:
            lines.append(
                f'note = "ELF $d run inside {symbol.name}, ROM '
                f'0x{run_start:08x}..0x{run_end:08x}"'
            )

    output = args.output.expanduser().resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"{symbol.name} 0x{args.func:08x} size 0x{size:x} -> "
          f"0x{args.runtime:08x}")
    print(f"image SHA-1 {image_sha1}")
    print(f"runs: {sum(1 for r in runs if r[2])} code, "
          f"{sum(1 for r in runs if not r[2])} data")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
