#!/usr/bin/env python3
"""Generate and optionally compile every hash-gated Golden Sun overlay."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path
import shutil
import subprocess
import sys

from import_main_symbols import SHF_EXECINSTR, parse_elf32_arm


def _symbol_signature(corpus: dict, overlay_id: str) -> tuple:
    return tuple(
        sorted(
            (
                entry["runtime_address"],
                entry["mode"],
                int(entry["size"]),
                entry["confidence"],
            )
            for entry in corpus["symbols"]
            if entry["overlay_id"] == overlay_id
            and entry["confidence"] in ("proven", "unresolved")
        )
    )


def inventory_overlay(record: dict, overlay_root: Path, corpus: dict) -> dict:
    overlay_id = record["overlay_id"]
    root = overlay_root / overlay_id
    binary = (root / "orig.bin").read_bytes()
    elf_bytes = (root / "overlay.elf").read_bytes()
    actual_sha256 = hashlib.sha256(binary).hexdigest()
    if actual_sha256 != record["source"]["decompressed_sha256"]:
        raise ValueError(f"{overlay_id}: decompressed SHA-256 mismatch")
    start = int(record["runtime"]["start"], 16)
    if len(binary) != int(record["runtime"]["loaded_size"]):
        raise ValueError(f"{overlay_id}: decompressed size mismatch")
    executable = [
        section
        for section in parse_elf32_arm(elf_bytes).sections
        if section.flags & SHF_EXECINSTR and section.size
    ]
    if len(executable) != 1 or executable[0].address != start:
        raise ValueError(f"{overlay_id}: expected one executable section at load start")
    text = executable[0]
    offset = text.address - start
    if offset < 0 or offset + text.size > len(binary):
        raise ValueError(f"{overlay_id}: executable section is outside loaded bytes")
    if elf_bytes[text.offset : text.offset + text.size] != binary[offset : offset + text.size]:
        raise ValueError(f"{overlay_id}: ELF executable bytes differ from orig.bin")
    signature = _symbol_signature(corpus, overlay_id)
    if not signature:
        raise ValueError(f"{overlay_id}: no verified ELF function entries")
    return {
        "id": overlay_id,
        "root": root,
        "start": start,
        "end": start + text.size,
        "text_sha1": hashlib.sha1(binary[offset : offset + text.size]).hexdigest(),
        "signature": signature,
        "seed_count": len(signature),
    }


def render_registry(inventories: list[dict], aliases: dict[str, list[str]]) -> str:
    lines = [
        "// Generated by tools/build_all_overlays.py from hash-gated pinned metadata.",
        "// Format: GSR_OVERLAY(id, start, text_end, text_sha1)",
    ]
    for item in inventories:
        alias_note = aliases.get(item["id"], [])
        if alias_note:
            lines.append(f"// Also identifies equivalent code image(s): {', '.join(alias_note)}")
        lines.append(
            f'GSR_OVERLAY({item["id"]}, 0x{item["start"]:08X}u, '
            f'0x{item["end"]:08X}u, "{item["text_sha1"]}")'
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--overlay-root", type=Path, default=Path("../goldensun-disasm/overlays"))
    parser.add_argument("--manifest", type=Path, default=Path("local/symbols/overlay-manifest.json"))
    parser.add_argument("--corpus", type=Path, default=Path("local/symbols/overlay-symbols.json"))
    parser.add_argument("--config-dir", type=Path, default=Path("config/usa/overlays"))
    parser.add_argument("--registry", type=Path, default=Path("config/usa/overlay-registry.inc"))
    parser.add_argument("--out-root", type=Path, default=Path("local/gs011"))
    parser.add_argument("--recompiler", type=Path)
    compile_mode = parser.add_mutually_exclusive_group()
    compile_mode.add_argument("--compile", action="store_true")
    compile_mode.add_argument("--compile-only", action="store_true")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    if (args.compile or args.compile_only) and args.recompiler is None:
        parser.error("compilation requires --recompiler")

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    corpus = json.loads(args.corpus.read_text(encoding="utf-8"))
    records = sorted(manifest["overlays"], key=lambda item: item["overlay_id"])
    all_items = [inventory_overlay(record, args.overlay_root, corpus) for record in records]

    canonical: dict[tuple[int, int, str], dict] = {}
    aliases: dict[str, list[str]] = {}
    unique: list[dict] = []
    for item in all_items:
        key = (item["start"], item["end"], item["text_sha1"])
        prior = canonical.get(key)
        if prior is None:
            canonical[key] = item
            unique.append(item)
        else:
            if prior["signature"] != item["signature"]:
                raise ValueError(
                    f'{item["id"]}: duplicate code identity has different dispatch metadata'
                )
            aliases.setdefault(prior["id"], []).append(item["id"])

    args.config_dir.mkdir(parents=True, exist_ok=True)
    for index, item in enumerate(all_items, 1):
        if args.compile_only:
            continue
        observed = Path("config/usa") / f'overlay-{item["id"].replace("_", "-")}-observed-entries.json'
        command = [
            sys.executable,
            str(Path(__file__).with_name("build_overlay_toml.py")),
            "--overlay-id", item["id"],
            "--binary", str(item["root"] / "orig.bin"),
            "--elf", str(item["root"] / "overlay.elf"),
            "--manifest", str(args.manifest),
            "--corpus", str(args.corpus),
            "--output", str(args.config_dir / f'{item["id"]}.toml'),
        ]
        command += ["--observed", str(observed)] if observed.exists() else ["--proactive"]
        subprocess.run(command, check=True, stdout=subprocess.DEVNULL)
        config_path = args.config_dir / f'{item["id"]}.toml'
        text = config_path.read_text(encoding="utf-8")
        shards = min(32, max(1, math.ceil(item["seed_count"] / 32)))
        config_path.write_text(
            text.replace("codegen_shards = 1", f"codegen_shards = {shards}", 1),
            encoding="utf-8", newline="\n",
        )
        print(f'config {index:02d}/{len(all_items)} {item["id"]} seeds={item["seed_count"]} shards={shards}')

    if not args.compile_only:
        args.registry.write_text(
            render_registry(unique, aliases), encoding="utf-8", newline="\n"
        )

    if args.compile or args.compile_only:
        recompiler_sha256 = hashlib.sha256(args.recompiler.read_bytes()).hexdigest()
        tool_sha256 = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()
        for index, item in enumerate(unique, 1):
            final_dir = args.out_root / f'overlay_{item["id"]}'
            config_path = args.config_dir / f'{item["id"]}.toml'
            fingerprint = hashlib.sha256(
                config_path.read_bytes()
                + item["text_sha1"].encode("ascii")
                + recompiler_sha256.encode("ascii")
                + tool_sha256.encode("ascii")
            ).hexdigest()
            stamp_path = final_dir / ".bulk-overlay-fingerprint"
            if (
                not args.force
                and (final_dir / "recompiled.h").exists()
                and (final_dir / "dispatch_table.cpp").exists()
                and stamp_path.exists()
                and stamp_path.read_text(encoding="ascii").strip() == fingerprint
            ):
                print(f'compile {index:02d}/{len(unique)} {item["id"]} (cached)')
                continue
            stage_dir = args.out_root / ".overlay-stage" / f'overlay_{item["id"]}'
            if stage_dir.exists():
                shutil.rmtree(stage_dir)
            stage_dir.mkdir(parents=True)
            subprocess.run(
                [
                    str(args.recompiler),
                    "--rom", str(item["root"] / "orig.bin"),
                    "--rom-base", f'0x{item["start"]:08X}',
                    "--config", str(config_path),
                    "--out", str(stage_dir),
                    "--symbol-prefix", f'gsr_overlay_{item["id"]}_',
                ],
                check=True,
                stdout=subprocess.DEVNULL,
            )
            if final_dir.exists():
                shutil.rmtree(final_dir)
            stage_dir.replace(final_dir)
            (final_dir / ".bulk-overlay-fingerprint").write_text(
                fingerprint + "\n", encoding="ascii", newline="\n"
            )
            print(f'compile {index:02d}/{len(unique)} {item["id"]}')
    print(f"Generated {len(all_items)} overlays / {len(unique)} unique code identities")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
