#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace gsr::blitter_shadow {

// Exact USA/Europe addresses established from the hash-gated corpus.  This is
// an observer only: it never changes guest state or replaces generated code.
inline constexpr std::uint32_t kBuilderEntry = 0x080ED408u;  // THUMB
inline constexpr std::uint32_t kAllocatorEntry = 0x080048B0u;  // THUMB
inline constexpr std::uint32_t kSlotTable = 0x03001E50u;
inline constexpr std::uint32_t kIwramEnd = 0x03008000u;
inline constexpr std::size_t kMaxSlots = 64;
inline constexpr std::size_t kMaxFingerprintsPerSlot = 16;

struct SlotStats {
    bool used = false;
    std::uint32_t slot = 0;
    std::uint32_t descriptor_hash = 0;
    std::uint32_t requested_bytes = 0;
    std::uint32_t last_entry = 0;
    std::uint64_t builder_calls = 0;
    std::uint64_t allocator_calls = 0;
    std::uint64_t descriptor_changes = 0;
    std::uint64_t arm_dispatches = 0;
    std::uint64_t wrong_mode_dispatches = 0;
    std::uint64_t entry_changes = 0;
    std::uint64_t fingerprint_overflow = 0;
    std::array<std::uint32_t, kMaxFingerprintsPerSlot> fingerprints{};
    std::size_t fingerprint_count = 0;
};

class Observer {
public:
    void builder_entry(std::uint32_t r0, std::uint32_t r1,
                       std::uint32_t r2, std::uint32_t r3,
                       std::uint32_t stack_arg0) {
        SlotStats& s = slot_for(r0);
        const std::uint32_t hash = descriptor_hash(r0, r1, r2, r3, stack_arg0);
        if (s.builder_calls != 0 && s.descriptor_hash != hash) {
            ++s.descriptor_changes;
        }
        s.descriptor_hash = hash;
        ++s.builder_calls;
        pending_slot_ = r0;
        pending_valid_ = true;
    }

    void allocator_entry(std::uint32_t slot, std::uint32_t requested_bytes) {
        if (!pending_valid_ || slot != pending_slot_) return;
        SlotStats& s = slot_for(slot);
        s.requested_bytes = requested_bytes;
        ++s.allocator_calls;
        pending_valid_ = false;
    }

    // slot_entry is the live word at 0x03001E50 + slot*4.  The caller reads
    // it through the canonical bus.  fingerprint is a one-way digest over the
    // allocator-requested span; no generated bytes are retained or logged.
    bool generated_dispatch(std::uint32_t pc, bool thumb,
                            std::uint32_t slot_entry,
                            std::uint32_t fingerprint,
                            std::uint32_t slot) {
        SlotStats* s = find_slot(slot);
        if (!s || slot_entry == 0 || s->requested_bytes == 0 ||
            pc < slot_entry ||
            static_cast<std::uint64_t>(pc) >=
                static_cast<std::uint64_t>(slot_entry) + s->requested_bytes) {
            return false;
        }
        if (thumb) {
            ++s->wrong_mode_dispatches;
            return false;
        }
        if (s->arm_dispatches != 0 && s->last_entry != pc) ++s->entry_changes;
        s->last_entry = pc;
        ++s->arm_dispatches;
        for (std::size_t i = 0; i < s->fingerprint_count; ++i) {
            if (s->fingerprints[i] == fingerprint) return true;
        }
        if (s->fingerprint_count < s->fingerprints.size()) {
            s->fingerprints[s->fingerprint_count++] = fingerprint;
        } else {
            ++s->fingerprint_overflow;
        }
        return true;
    }

    const std::array<SlotStats, kMaxSlots>& slots() const { return slots_; }
    std::uint64_t evictions() const { return evictions_; }

    static bool slot_address(std::uint32_t slot, std::uint32_t* out) {
        const std::uint64_t addr = static_cast<std::uint64_t>(kSlotTable) +
                                   static_cast<std::uint64_t>(slot) * 4u;
        if (addr + 4u > kIwramEnd) return false;
        if (out) *out = static_cast<std::uint32_t>(addr);
        return true;
    }

    static std::uint32_t bytes_hash(const std::uint8_t* data,
                                    std::size_t size) {
        std::uint32_t h = 2166136261u;
        for (std::size_t i = 0; i < size; ++i) {
            h = (h ^ data[i]) * 16777619u;
        }
        return h;
    }

private:
    static std::uint32_t descriptor_hash(std::uint32_t a, std::uint32_t b,
                                         std::uint32_t c, std::uint32_t d,
                                         std::uint32_t e) {
        const std::uint32_t words[] = {a, b, c, d, e};
        return bytes_hash(reinterpret_cast<const std::uint8_t*>(words),
                          sizeof(words));
    }

    SlotStats* find_slot(std::uint32_t slot) {
        for (auto& s : slots_) if (s.used && s.slot == slot) return &s;
        return nullptr;
    }

    SlotStats& slot_for(std::uint32_t slot) {
        if (SlotStats* s = find_slot(slot)) return *s;
        for (auto& s : slots_) {
            if (!s.used) {
                s.used = true;
                s.slot = slot;
                return s;
            }
        }
        ++evictions_;
        const std::size_t index = static_cast<std::size_t>(slot) % slots_.size();
        slots_[index] = {};
        slots_[index].used = true;
        slots_[index].slot = slot;
        return slots_[index];
    }

    std::array<SlotStats, kMaxSlots> slots_{};
    std::uint32_t pending_slot_ = 0;
    bool pending_valid_ = false;
    std::uint64_t evictions_ = 0;
};

}  // namespace gsr::blitter_shadow
